name: MY GHA

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Process Images and Build
              run: |
                mkdir dist
                cp index.html dist/
                
                echo "{}" > dist/manifest.json
      
                for file in assets/*; do
                  if [ -f "$file" ]; then
                    ext="${file##*.}"
                    hash=$(sha256sum "$file" | awk '{print $1}' | cut -c 1-32)
                    new_name="${hash}.${ext}"
                    
                    cp "$file" "dist/$new_name"
            
                    filename=$(basename "$file")
                    jq --arg k "$filename" --arg v "$new_name" '.[$k] = $v' dist/manifest.json > dist/tmp.json
                    mv dist/tmp.json dist/manifest.json
                  fi
                done

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4